sudo: required
services:
  - docker

before_install:
  - docker build -t andrespulecio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrespulecio/react-test npm test
  # - docker run react-test npm test -- --coverage

after_success:
  - docker build -t andrespulecio/multi-client ./client
  - docker build -t andrespulecio/multi-nginx ./nginx
  - docker build -t andrespulecio/multi-server ./server
  - docker build -t andrespulecio/multi-worker ./worker  
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push andrespulecio/multi-client 
  - docker push andrespulecio/multi-nginx 
  - docker push andrespulecio/multi-server 
  - docker push andrespulecio/multi-worker 
  
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-630942828381
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  

